### ISSUE TITLE
not found cocoapods-bazel

### ISSUE THREAD

**Issue by yishuiliunian** [bazel-ios/cocoapods-bazel#36]
using Gemfile with 

```
gem 'cocoapods-bazel'
```

after run 'bundle install' , there an error occurs 

```
Could not find gem 'cocoapods-bazel' in any of the gem sources listed in your Gemfile.
```

**Comment by thiagohmcruz** [comment]
Hi @yishuiliunian, I think different things could be causing this issue. Would you be able to share your `Gemfile` and `Gemfile.lock` and also the output of `bundle env`?

Also, are you able to install it directly?
```sh
gem install cocoapods-bazel
```

**Comment by yishuiliunian** [comment]
my gemfile :

```
source 'http://rubygems.cocoadepot.top'
source 'http://rubygems.org'
gem 'cocoadepot'
gem 'cocoadepot-runner'
gem 'cocoadepot-platform'
gem 'cocoapods-bazel'

```

and i can not able to install it directly

**Comment by yishuiliunian** [comment]
and i can not found the gem 'cocoapods-bazel' in https://rubygems.org

![image](https://user-images.githubusercontent.com/846525/118763834-17042c80-b8ab-11eb-8402-1d4202207131.png)

**Comment by thiagohmcruz** [comment]
@yishuiliunian putting this in your `Gemfile` and let me know:
```ruby
gem 'cocoapods-bazel', git: 'https://github.com/bazel-ios/cocoapods-bazel.git'
```

**Comment by yishuiliunian** [comment]
> @yishuiliunian putting this in your `Gemfile` and let me know:
> 
> ```ruby
> gem 'cocoapods-bazel', git: 'https://github.com/bazel-ios/cocoapods-bazel.git'
> ```

it can fix the problem. and will you publish the gem to the rubygems.org?

**Comment by justinseanmartin** [comment]
At this time, we're doing our development from the top of HEAD and not explicitly releasing versions of this gem.
